//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Careers_locators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Careers_locators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.Careers_locators", typeof(Careers_locators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button-blue.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .hidden-sm-down.col-md-2 &gt; [name=&apos;button&apos;].
        /// </summary>
        internal static string apply_job {
            get {
                return ResourceManager.GetString("apply_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.nav-modal-links-contain div:nth-of-type(5) .nav-modal-link.
        /// </summary>
        internal static string Career_center {
            get {
                return ResourceManager.GetString("Career_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/app-root/div/div/app-my-job-posting/div/div[2]/div/div[1]/div/div/span.
        /// </summary>
        internal static string career_center_bc {
            get {
                return ResourceManager.GetString("career_center_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul.col-12 li:nth-of-type(3) .inner-text.
        /// </summary>
        internal static string community {
            get {
                return ResourceManager.GetString("community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [placeholder=&apos;Company Name&apos;].
        /// </summary>
        internal static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;col-md-2 hidden-sm-down col-12 button-section ng-star-inserted&apos;]/button[@name=&apos;button&apos;].
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button-blue.
        /// </summary>
        internal static string confirm_popup {
            get {
                return ResourceManager.GetString("confirm_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Em {
            get {
                return ResourceManager.GetString("Em", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[formcontrolname=&apos;resumeEmail&apos;].
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;mat-tab-label mat-ripple ng-star-inserted&apos;]/div[@class=&apos;mat-tab-label-content&apos;].
        /// </summary>
        internal static string Employer_Tab {
            get {
                return ResourceManager.GetString("Employer_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string enter_text {
            get {
                return ResourceManager.GetString("enter_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cke_wysiwyg_frame.
        /// </summary>
        internal static string iframe {
            get {
                return ResourceManager.GetString("iframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[formcontrolname=&apos;name&apos;].
        /// </summary>
        internal static string job_title {
            get {
                return ResourceManager.GetString("job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mat-simple-snackbar.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #modal-content &gt; div.row.justify-content-center &gt; div &gt; div &gt; button.col-md-5.col-11.button-blue.
        /// </summary>
        internal static string my_job_posting {
            get {
                return ResourceManager.GetString("my_job-posting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a[href=&apos;/community/career-center/job-posting&apos;].
        /// </summary>
        internal static string post_job {
            get {
                return ResourceManager.GetString("post_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;col-md-2 hidden-sm-down col-12 button-section&apos;]/button[@name=&apos;button&apos;].
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button.
        /// </summary>
        internal static string search_btn {
            get {
                return ResourceManager.GetString("search_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-option[aria-selected=&apos;true&apos;].
        /// </summary>
        internal static string select_job {
            get {
                return ResourceManager.GetString("select_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.browse-page-results-section &gt; div:nth-of-type(4) h3.
        /// </summary>
        internal static string select_posted_job {
            get {
                return ResourceManager.GetString("select_posted_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mat-select-trigger.
        /// </summary>
        internal static string select_resume {
            get {
                return ResourceManager.GetString("select_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-option[aria-selected=&apos;true&apos;].
        /// </summary>
        internal static string selected_resume {
            get {
                return ResourceManager.GetString("selected_resume", resourceCulture);
            }
        }
    }
}
