//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class competition_locators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal competition_locators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.competition_locators", typeof(competition_locators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul.col-12 li:nth-of-type(3) .inner-text.
        /// </summary>
        internal static string community_locators {
            get {
                return ResourceManager.GetString("community_locators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;nav-modal-links-contain&apos;]//div[@class=&apos;nav-modal-link-bar ng-star-inserted&apos;]/div[contains(.,&apos;Competitions&apos;)].
        /// </summary>
        internal static string competition {
            get {
                return ResourceManager.GetString("competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .edit-button.
        /// </summary>
        internal static string edit_entry {
            get {
                return ResourceManager.GetString("edit_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.enter-now &gt; .button.
        /// </summary>
        internal static string enter_btn {
            get {
                return ResourceManager.GetString("enter_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-placeholder[_ngcontent-c41].
        /// </summary>
        internal static string Entry_form {
            get {
                return ResourceManager.GetString("Entry_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [placeholder].
        /// </summary>
        internal static string EntryName {
            get {
                return ResourceManager.GetString("EntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a[xpath=&apos;1&apos;].
        /// </summary>
        internal static string free_comptetion {
            get {
                return ResourceManager.GetString("free_comptetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[color=&apos;white&apos;].
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[color=&apos;white&apos;].
        /// </summary>
        internal static string my_comp_enteries {
            get {
                return ResourceManager.GetString("my_comp_enteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button-blue.
        /// </summary>
        internal static string next_btn {
            get {
                return ResourceManager.GetString("next_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[xpath=&apos;1&apos;].
        /// </summary>
        internal static string open_comptetion {
            get {
                return ResourceManager.GetString("open_comptetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;button button-blue&apos;].
        /// </summary>
        internal static string submit_btn {
            get {
                return ResourceManager.GetString("submit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-table.mat-table &gt; mat-row:nth-of-type(5) .my-competition-action.
        /// </summary>
        internal static string view_btn {
            get {
                return ResourceManager.GetString("view_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.nav-modal-links-contain div:nth-of-type(2) &gt; .nav-modal-link.
        /// </summary>
        internal static string view_competetion_enteries {
            get {
                return ResourceManager.GetString("view_competetion_enteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;nav-modal-links-contain&apos;]//div[@class=&apos;nav-modal-link-bar ng-star-inserted&apos;]/div[contains(.,&apos;View Open Competitions&apos;)].
        /// </summary>
        internal static string view_competitions {
            get {
                return ResourceManager.GetString("view_competitions", resourceCulture);
            }
        }
    }
}
