//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.config", typeof(config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4111111111111111.
        /// </summary>
        internal static string BlueCreditCardNumber {
            get {
                return ResourceManager.GetString("BlueCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string BlueDelayPrompt {
            get {
                return ResourceManager.GetString("BlueDelayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string BlueDelayScreenChange {
            get {
                return ResourceManager.GetString("BlueDelayScreenChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9000.
        /// </summary>
        internal static string BlueDelayWaitOnMyAccount {
            get {
                return ResourceManager.GetString("BlueDelayWaitOnMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string BlueDelayWaitOnSelection {
            get {
                return ResourceManager.GetString("BlueDelayWaitOnSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09.
        /// </summary>
        internal static string BlueExpMonth {
            get {
                return ResourceManager.GetString("BlueExpMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string BlueExpYear {
            get {
                return ResourceManager.GetString("BlueExpYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leesa Blue Assoc.
        /// </summary>
        internal static string BlueLoginPageTitle {
            get {
                return ResourceManager.GetString("BlueLoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string BlueNameOnCard {
            get {
                return ResourceManager.GetString("BlueNameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te$t1234.
        /// </summary>
        internal static string BluePassword {
            get {
                return ResourceManager.GetString("BluePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 444.
        /// </summary>
        internal static string BlueSecCode {
            get {
                return ResourceManager.GetString("BlueSecCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://jbba.users.dev.membersuite.com/home.
        /// </summary>
        internal static string BlueUrl {
            get {
                return ResourceManager.GetString("BlueUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sticky.
        /// </summary>
        internal static string BlueUsername {
            get {
                return ResourceManager.GetString("BlueUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox.
        /// </summary>
        internal static string BrowserToRunWith {
            get {
                return ResourceManager.GetString("BrowserToRunWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4111111111111111.
        /// </summary>
        internal static string GreenCreditCardNumber {
            get {
                return ResourceManager.GetString("GreenCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string GreenDelayPrompt {
            get {
                return ResourceManager.GetString("GreenDelayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string GreenDelayScreenChange {
            get {
                return ResourceManager.GetString("GreenDelayScreenChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9000.
        /// </summary>
        internal static string GreenDelayWaitOnMyAccount {
            get {
                return ResourceManager.GetString("GreenDelayWaitOnMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string GreenDelayWaitOnSelection {
            get {
                return ResourceManager.GetString("GreenDelayWaitOnSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09.
        /// </summary>
        internal static string GreenExpMonth {
            get {
                return ResourceManager.GetString("GreenExpMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string GreenExpYear {
            get {
                return ResourceManager.GetString("GreenExpYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelly Gills Green Assoc.
        /// </summary>
        internal static string GreenLoginPageTitle {
            get {
                return ResourceManager.GetString("GreenLoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string GreenNameOnCard {
            get {
                return ResourceManager.GetString("GreenNameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te$t1234.
        /// </summary>
        internal static string GreenPassword {
            get {
                return ResourceManager.GetString("GreenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 444.
        /// </summary>
        internal static string GreenSecCode {
            get {
                return ResourceManager.GetString("GreenSecCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kellygreen.users.financial.membersuite.com/home.
        /// </summary>
        internal static string GreenUrl {
            get {
                return ResourceManager.GetString("GreenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doxie.
        /// </summary>
        internal static string GreenUsername {
            get {
                return ResourceManager.GetString("GreenUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\MemberSuite\Logs.
        /// </summary>
        internal static string LoggingPath {
            get {
                return ResourceManager.GetString("LoggingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 377936422423475.
        /// </summary>
        internal static string ProdCreditCardNumber {
            get {
                return ResourceManager.GetString("ProdCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string ProdDelayPrompt {
            get {
                return ResourceManager.GetString("ProdDelayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6000.
        /// </summary>
        internal static string ProdDelayScreenChange {
            get {
                return ResourceManager.GetString("ProdDelayScreenChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9000.
        /// </summary>
        internal static string ProdDelayWaitOnMyAccount {
            get {
                return ResourceManager.GetString("ProdDelayWaitOnMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000.
        /// </summary>
        internal static string ProdDelayWaitOnSelection {
            get {
                return ResourceManager.GetString("ProdDelayWaitOnSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ProdExpMonth {
            get {
                return ResourceManager.GetString("ProdExpMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string ProdExpYear {
            get {
                return ResourceManager.GetString("ProdExpYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelly Gills PRD 2020.
        /// </summary>
        internal static string ProdLoginPageTitle {
            get {
                return ResourceManager.GetString("ProdLoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string ProdNameOnCard {
            get {
                return ResourceManager.GetString("ProdNameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te$t1234.
        /// </summary>
        internal static string ProdPassword {
            get {
                return ResourceManager.GetString("ProdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8344.
        /// </summary>
        internal static string ProdSecCode {
            get {
                return ResourceManager.GetString("ProdSecCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kellyprd.users.membersuite.com/home.
        /// </summary>
        internal static string ProdUrl {
            get {
                return ResourceManager.GetString("ProdUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorrel.
        /// </summary>
        internal static string ProdUsername {
            get {
                return ResourceManager.GetString("ProdUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string RunEnvironment {
            get {
                return ResourceManager.GetString("RunEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\MemberSuite\Screens.
        /// </summary>
        internal static string ScreenCapturePath {
            get {
                return ResourceManager.GetString("ScreenCapturePath", resourceCulture);
            }
        }
    }
}
