//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class directory_locators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal directory_locators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.directory_locators", typeof(directory_locators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;cdk-accordion-child-1&quot;]/div/form/button/i.
        /// </summary>
        internal static string apply_btn {
            get {
                return ResourceManager.GetString("apply_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;back-button ng-star-inserted&apos;].
        /// </summary>
        internal static string back_results {
            get {
                return ResourceManager.GetString("back_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.nav-modal-links-contain &gt; [_ngcontent-c12] &gt; div:nth-of-type(1) .nav-modal-link.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .col-md-12.
        /// </summary>
        internal static string down_arrow {
            get {
                return ResourceManager.GetString("down_arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .member-name.
        /// </summary>
        internal static string member_selection {
            get {
                return ResourceManager.GetString("member_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //mat-form-field[@class=&apos;mat-input-container mat-form-field ng-tns-c15-6 mat-primary mat-form-field-type-mat-input mat-form-field-can-float mat-form-field-hide-placeholder ng-pristine ng-valid ng-star-inserted ng-touched&apos;]//div[@class=&apos;mat-input-infix mat-form-field-infix&apos;].
        /// </summary>
        internal static string search_field {
            get {
                return ResourceManager.GetString("search_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;mat-expansion-panel-content ng-trigger ng-trigger-bodyExpansion mat-expanded&apos;]//input[@name=&apos;searchTerms&apos;].
        /// </summary>
        internal static string search_input {
            get {
                return ResourceManager.GetString("search_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[.=&apos;Apple Watch&apos;].
        /// </summary>
        internal static string select_profile {
            get {
                return ResourceManager.GetString("select_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;mat-expansion-indicator ng-tns-c24-13 ng-trigger ng-trigger-indicatorRotate ng-star-inserted&apos;].
        /// </summary>
        internal static string updown {
            get {
                return ResourceManager.GetString("updown", resourceCulture);
            }
        }
    }
}
