//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events_locator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events_locator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.Events_locator", typeof(Events_locator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[contains(.,&apos;Next&apos;)].
        /// </summary>
        internal static string _2nd_nxt_btn {
            get {
                return ResourceManager.GetString("2nd_nxt_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button.
        /// </summary>
        internal static string Addcart {
            get {
                return ResourceManager.GetString("Addcart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.nav-modal-links-contain &gt; [_ngcontent-c12] &gt; div:nth-of-type(1) .nav-modal-link.
        /// </summary>
        internal static string browse_events {
            get {
                return ResourceManager.GetString("browse_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-expansion-panel-header[aria-controls=&apos;cdk-accordion-child-1&apos;] &gt; .mat-expansion-indicator.
        /// </summary>
        internal static string click_accordion {
            get {
                return ResourceManager.GetString("click_accordion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #mat-expansion-panel-header-2 &gt; .mat-content.
        /// </summary>
        internal static string down_arrow {
            get {
                return ResourceManager.GetString("down_arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;email&apos;].
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [placeholder].
        /// </summary>
        internal static string enetr_answer {
            get {
                return ResourceManager.GetString("enetr_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[aria-labelledby=&apos;mat-expansion-panel-header-2&apos;] [placeholder].
        /// </summary>
        internal static string enter_age1 {
            get {
                return ResourceManager.GetString("enter_age1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[aria-labelledby=&apos;mat-expansion-panel-header-3&apos;] [placeholder].
        /// </summary>
        internal static string enter_age2 {
            get {
                return ResourceManager.GetString("enter_age2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul.col-12 li:nth-of-type(2) .inner-text.
        /// </summary>
        internal static string Eventts_tab {
            get {
                return ResourceManager.GetString("Eventts_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;firstName&apos;].
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;lastName&apos;].
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button.button-blue.
        /// </summary>
        internal static string next_btn {
            get {
                return ResourceManager.GetString("next_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[_ngcontent-c42].
        /// </summary>
        internal static string next_btn_event_select {
            get {
                return ResourceManager.GetString("next_btn_event_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.register &gt; .button.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;role&apos;].
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .contacts-view.
        /// </summary>
        internal static string scroll_div {
            get {
                return ResourceManager.GetString("scroll_div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[_ngcontent-c38].
        /// </summary>
        internal static string select_btn {
            get {
                return ResourceManager.GetString("select_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[data-test=&apos;package-select-button-0&apos;].
        /// </summary>
        internal static string select_contact1 {
            get {
                return ResourceManager.GetString("select_contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[data-test=&apos;package-select-button-1&apos;].
        /// </summary>
        internal static string select_contact2 {
            get {
                return ResourceManager.GetString("select_contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[data-test=&apos;event-name-2&apos;].
        /// </summary>
        internal static string select_events {
            get {
                return ResourceManager.GetString("select_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.mat-select-content &gt; mat-option:nth-of-type(2).
        /// </summary>
        internal static string select_role {
            get {
                return ResourceManager.GetString("select_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .submit-button.
        /// </summary>
        internal static string submitbtn {
            get {
                return ResourceManager.GetString("submitbtn", resourceCulture);
            }
        }
    }
}
