//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locator_profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locator_profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.locator_profile", typeof(locator_profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[id*=&apos;cdk-overlay&apos;].
        /// </summary>
        internal static string action_locator {
            get {
                return ResourceManager.GetString("action_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[placeholder=&apos;Street 1&apos;].
        /// </summary>
        internal static string address_field {
            get {
                return ResourceManager.GetString("address_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label[for=&apos;mat-radio-7-input&apos;] &gt; .mat-radio-container.
        /// </summary>
        internal static string address_radio {
            get {
                return ResourceManager.GetString("address_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .name.
        /// </summary>
        internal static string assert_profile {
            get {
                return ResourceManager.GetString("assert_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [placeholder=&apos;City&apos;].
        /// </summary>
        internal static string city_field {
            get {
                return ResourceManager.GetString("city_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-select[data-test=&apos;input-country&apos;].
        /// </summary>
        internal static string country_select {
            get {
                return ResourceManager.GetString("country_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.mat-select-content &gt; mat-option:nth-of-type(1) &gt; .mat-option-text.
        /// </summary>
        internal static string country_value {
            get {
                return ResourceManager.GetString("country_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //menu[@class=&apos;dropdown expanded&apos;]/ul[@class=&apos;wrapper&apos;].
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@class=&apos;ng-untouched ng-pristine ng-valid&apos;]//img[@alt=&apos;pencil&apos;].
        /// </summary>
        internal static string edit_btn {
            get {
                return ResourceManager.GetString("edit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[data-test=&apos;question-1&apos;].
        /// </summary>
        internal static string field_age {
            get {
                return ResourceManager.GetString("field_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[data-test=&apos;question-3&apos;].
        /// </summary>
        internal static string field_born {
            get {
                return ResourceManager.GetString("field_born", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;lastName&apos;].
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;modal-content background-customizable modal-content-mobile visible-md visible-lg&apos;]//input[@name=&apos;signInSubmitButton&apos;].
        /// </summary>
        internal static string Login_btn {
            get {
                return ResourceManager.GetString("Login_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //menu[@class=&apos;dropdown expanded&apos;]//a[contains(.,&apos;Login&apos;)].
        /// </summary>
        internal static string login_menu {
            get {
                return ResourceManager.GetString("login_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;modal-content background-customizable modal-content-mobile visible-md visible-lg&apos;]//input[@id=&apos;signInFormPassword&apos;].
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        internal static string phone_num {
            get {
                return ResourceManager.GetString("phone_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label[for=&apos;mat-radio-3-input&apos;] &gt; .mat-radio-container.
        /// </summary>
        internal static string phone_radio {
            get {
                return ResourceManager.GetString("phone_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;profile&apos;]//img[@style~=visibility].
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .compact:nth-child(3) .icon-cross-circle.
        /// </summary>
        internal static string remove_address {
            get {
                return ResourceManager.GetString("remove_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;container-fluid contact-info none&apos;]//div[3]//span[@class=&apos;icon-cross-circle ng-star-inserted&apos;].
        /// </summary>
        internal static string remove_phone {
            get {
                return ResourceManager.GetString("remove_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .add-btn.
        /// </summary>
        internal static string save_phone {
            get {
                return ResourceManager.GetString("save_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-select[data-test=&apos;input-state&apos;].
        /// </summary>
        internal static string state_select {
            get {
                return ResourceManager.GetString("state_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.mat-select-content &gt; mat-option:nth-of-type(2) &gt; .mat-option-text.
        /// </summary>
        internal static string state_value {
            get {
                return ResourceManager.GetString("state_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button-blue.
        /// </summary>
        internal static string update_btn {
            get {
                return ResourceManager.GetString("update_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .left-confirmation-button.
        /// </summary>
        internal static string update_profile_btn {
            get {
                return ResourceManager.GetString("update_profile_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;modal-content background-customizable modal-content-mobile visible-md visible-lg&apos;]//input[@id=&apos;signInFormUsername&apos;].
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[contains(.,&apos;Validate and Save Address&apos;)].
        /// </summary>
        internal static string validate_address {
            get {
                return ResourceManager.GetString("validate_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [placeholder=&apos;Zip Code&apos;].
        /// </summary>
        internal static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
