//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class membership_locator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal membership_locator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.membership_locator", typeof(membership_locator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .change-link.
        /// </summary>
        internal static string change_chapter {
            get {
                return ResourceManager.GetString("change_chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .chapter.
        /// </summary>
        internal static string chapters {
            get {
                return ResourceManager.GetString("chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;button button-blue button-promo-code mat-raised-button mat-primary ng-star-inserted&apos;].
        /// </summary>
        internal static string checkbox_click {
            get {
                return ResourceManager.GetString("checkbox_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button.
        /// </summary>
        internal static string checkpout_btn {
            get {
                return ResourceManager.GetString("checkpout_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;button button-blue&apos;].
        /// </summary>
        internal static string final_checkout_btn {
            get {
                return ResourceManager.GetString("final_checkout_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[aria-controls=&apos;mat-tab-content-0-1&apos;] &gt; .mat-tab-label-content.
        /// </summary>
        internal static string membership {
            get {
                return ResourceManager.GetString("membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button.
        /// </summary>
        internal static string next_btn {
            get {
                return ResourceManager.GetString("next_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .left-confirmation-button.
        /// </summary>
        internal static string okay_checkoutbtn {
            get {
                return ResourceManager.GetString("okay_checkoutbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //mat-radio-button[@class=&apos;col-12 col-sm-10 col-md-8 bottomPadding mat-radio-button mat-accent ng-star-inserted&apos;]//div[@class=&apos;mat-radio-container&apos;].
        /// </summary>
        internal static string radio_address_select {
            get {
                return ResourceManager.GetString("radio_address_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-checkbox.
        /// </summary>
        internal static string select_chapter_12 {
            get {
                return ResourceManager.GetString("select_chapter_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@name=&apos;chapter&apos;]//div[@class=&apos;chapter row hidden-sm-down change-chapter ng-star-inserted&apos;]//input[@value=&apos;eb12a7be-0073-cd35-d748-1692fa66d1fd&apos;].
        /// </summary>
        internal static string select_chpater_11 {
            get {
                return ResourceManager.GetString("select_chpater_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;row card-wrapper no-gutters membership-card&apos;]/div[@class=&apos;col-xs-12 col-md-10 col-xl-10 card-container contact-container chapter-card ng-star-inserted&apos;]/div[2]//span[contains(.,&apos;View Details&apos;)].
        /// </summary>
        internal static string view_details {
            get {
                return ResourceManager.GetString("view_details", resourceCulture);
            }
        }
    }
}
