//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyAccount_locators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyAccount_locators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.MyAccount_locators", typeof(MyAccount_locators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#saveAccountCreditCard .payment-new-option.
        /// </summary>
        internal static string add_bank_acc {
            get {
                return ResourceManager.GetString("add_bank_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#saveCreditCard &gt; .row .payment-new-option.
        /// </summary>
        internal static string add_debitcard {
            get {
                return ResourceManager.GetString("add_debitcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;achAccountNumber&apos;].
        /// </summary>
        internal static string bank_acc_no {
            get {
                return ResourceManager.GetString("bank_acc_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;cardExpMonth&apos;].
        /// </summary>
        internal static string bank_acc_type {
            get {
                return ResourceManager.GetString("bank_acc_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;achRoutingNumber&apos;].
        /// </summary>
        internal static string bank_routing_no {
            get {
                return ResourceManager.GetString("bank_routing_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mat-option.
        /// </summary>
        internal static string bank_type_select {
            get {
                return ResourceManager.GetString("bank_type_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;cardName&apos;].
        /// </summary>
        internal static string card_name {
            get {
                return ResourceManager.GetString("card_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;cardNumber&apos;].
        /// </summary>
        internal static string card_num {
            get {
                return ResourceManager.GetString("card_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;cardSecCode&apos;].
        /// </summary>
        internal static string cvv_code {
            get {
                return ResourceManager.GetString("cvv_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-expansion-panel-header[aria-controls=&apos;cdk-accordion-child-3&apos;] &gt; .mat-expansion-indicator.
        /// </summary>
        internal static string down_accordion {
            get {
                return ResourceManager.GetString("down_accordion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;cardExpMonth&apos;].
        /// </summary>
        internal static string exp_month {
            get {
                return ResourceManager.GetString("exp_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.mat-select-content mat-option:nth-of-type(4).
        /// </summary>
        internal static string exp_month_value {
            get {
                return ResourceManager.GetString("exp_month_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;cardExpYear&apos;].
        /// </summary>
        internal static string exp_year {
            get {
                return ResourceManager.GetString("exp_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.mat-select-content mat-option:nth-of-type(5).
        /// </summary>
        internal static string exp_year_value {
            get {
                return ResourceManager.GetString("exp_year_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #mat-tab-label-0-2 &gt; .mat-tab-label-content.
        /// </summary>
        internal static string My_Account {
            get {
                return ResourceManager.GetString("My_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.mat-expanded div:nth-of-type(4) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2).
        /// </summary>
        internal static string order_id {
            get {
                return ResourceManager.GetString("order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sub-text.
        /// </summary>
        internal static string print_invoice {
            get {
                return ResourceManager.GetString("print_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .save-button.
        /// </summary>
        internal static string save_bank_btn {
            get {
                return ResourceManager.GetString("save_bank_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button.save-button-profile.mat-raised-button.
        /// </summary>
        internal static string save_btn {
            get {
                return ResourceManager.GetString("save_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-expansion-panel-header[aria-controls=&apos;cdk-accordion-child-4&apos;] &gt; .mat-expansion-indicator.
        /// </summary>
        internal static string saved_payment_accordion {
            get {
                return ResourceManager.GetString("saved_payment_accordion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mat-select-panel.
        /// </summary>
        internal static string select_exp_month {
            get {
                return ResourceManager.GetString("select_exp_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mat-select-panel.
        /// </summary>
        internal static string select_exp_year {
            get {
                return ResourceManager.GetString("select_exp_year", resourceCulture);
            }
        }
    }
}
