//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class s_k_values {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal s_k_values() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.s_k_values", typeof(s_k_values).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _2ndemail {
            get {
                return ResourceManager.GetString("2ndemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 322 S Benjamin St.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77.
        /// </summary>
        internal static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 212121212121.
        /// </summary>
        internal static string bank_acc {
            get {
                return ResourceManager.GetString("bank_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 021000021.
        /// </summary>
        internal static string bank_routing {
            get {
                return ResourceManager.GetString("bank_routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1961.
        /// </summary>
        internal static string birth_year {
            get {
                return ResourceManager.GetString("birth_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_card.
        /// </summary>
        internal static string card_name {
            get {
                return ResourceManager.GetString("card_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4111111111111111.
        /// </summary>
        internal static string card_num {
            get {
                return ResourceManager.GetString("card_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stillwater.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick Builders.
        /// </summary>
        internal static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missy.
        /// </summary>
        internal static string contact_fname {
            get {
                return ResourceManager.GetString("contact_fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string contact_lname {
            get {
                return ResourceManager.GetString("contact_lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 444.
        /// </summary>
        internal static string cvv_code {
            get {
                return ResourceManager.GetString("cvv_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.test002@ymail.com.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missy.test001@gmail.com.
        /// </summary>
        internal static string email2 {
            get {
                return ResourceManager.GetString("email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to really free competition.
        /// </summary>
        internal static string entry {
            get {
                return ResourceManager.GetString("entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lego Masters.
        /// </summary>
        internal static string job__title {
            get {
                return ResourceManager.GetString("job _title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooper.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4055551212.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lego@mailintor.com.
        /// </summary>
        internal static string resume_send_email {
            get {
                return ResourceManager.GetString("resume_send_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job seeking infomation.
        /// </summary>
        internal static string rich_text {
            get {
                return ResourceManager.GetString("rich_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy Elf.
        /// </summary>
        internal static string search_value {
            get {
                return ResourceManager.GetString("search_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oklahoma.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 74074.
        /// </summary>
        internal static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
