//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRPTests.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shop_locators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shop_locators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRPTests.Config.Shop_locators", typeof(Shop_locators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.add-button-style &gt; .button.
        /// </summary>
        internal static string Add_tocart {
            get {
                return ResourceManager.GetString("Add_tocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .col-12.
        /// </summary>
        internal static string Assert_text {
            get {
                return ResourceManager.GetString("Assert_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.nav-modal-links-contain &gt; [_ngcontent-c12] &gt; div:nth-of-type(1) .nav-modal-link.
        /// </summary>
        internal static string browse_store {
            get {
                return ResourceManager.GetString("browse_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nav-cart.cart-icon .icon-cart.
        /// </summary>
        internal static string cart_icon_direct {
            get {
                return ResourceManager.GetString("cart_icon_direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button.
        /// </summary>
        internal static string checkout_btn {
            get {
                return ResourceManager.GetString("checkout_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[class=&apos;button button-blue&apos;].
        /// </summary>
        internal static string checkout_complete_btn {
            get {
                return ResourceManager.GetString("checkout_complete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button.col-12.
        /// </summary>
        internal static string close_btn {
            get {
                return ResourceManager.GetString("close_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button-blue.
        /// </summary>
        internal static string close_final {
            get {
                return ResourceManager.GetString("close_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .continue-to-cart.
        /// </summary>
        internal static string continue_cart {
            get {
                return ResourceManager.GetString("continue_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .button-white.
        /// </summary>
        internal static string continue_shopping {
            get {
                return ResourceManager.GetString("continue_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name=&apos;inputSearch&apos;].
        /// </summary>
        internal static string enter_detail {
            get {
                return ResourceManager.GetString("enter_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .largerImage[src=&apos;https://images.membersuite.com/eb12a7be-0004-c2c7-1b59-0b3fb87d8577/31961/eb12a7be-001c-c34a-d848-cf566c76f134&apos;].
        /// </summary>
        internal static string items_select_1st_ {
            get {
                return ResourceManager.GetString("items_select(1st)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .largerImage[src=&apos;https://images.membersuite.com/eb12a7be-0004-c2c7-1b59-0b3fb87d8577/31961/eb12a7be-001c-ca0e-d848-cbb3d09f0733&apos;].
        /// </summary>
        internal static string items_select_2nd_ {
            get {
                return ResourceManager.GetString("items_select(2nd)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .left-confirmation-button.
        /// </summary>
        internal static string okay_checkout_btn {
            get {
                return ResourceManager.GetString("okay_checkout_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label[for=&apos;mat-radio-5-input&apos;] &gt; .mat-radio-container.
        /// </summary>
        internal static string select_address {
            get {
                return ResourceManager.GetString("select_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label[for=&apos;mat-radio-7-input&apos;] &gt; .mat-radio-container.
        /// </summary>
        internal static string select_debit {
            get {
                return ResourceManager.GetString("select_debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label[for=&apos;mat-radio-8-input&apos;] &gt; .mat-radio-container.
        /// </summary>
        internal static string select_debit_electronic {
            get {
                return ResourceManager.GetString("select_debit_electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul.col-12 li:nth-of-type(4) .inner-text.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
    }
}
